#!/usr/bin/env python

"""Advent of Code 2022, Day 23 (Unit Tests)"""

import unittest

from d23 import parse, ground_tiles

example1 = """..............
..............
.......#......
.....###.#....
...#...#.#....
....#...##....
...#.###......
...##.#.##....
....#..#......
..............
..............
.............."""


class GroundTilesTests(unittest.TestCase):
    def test_example1(slf):
        slf.assertEqual(ground_tiles(parse(example1)), 110)


if __name__ == "__main__":
    unittest.main()
